[book]
title = "OceanGraph App Guide"
authors = ["OceanGraph Team"]
description = "Documentation for OceanGraph platform."
language = "en"

[output]
[output.html]
preferred-dark-theme = "navy"
default-theme = "light"
additional-js = ["mermaid.min.js", "mermaid-init.js"]
mathjax-support = true

[output.html.search]
enable = true
